from subprocess import run


def run_blastx(contig_file: str, others_db_path: str, sample: str,
               outfile_suffix: str) -> str:
    """
    Executes the BLASTx program with the specified parameters and returns the
    path to the resulting output file.

    Args:
        contig_file (str): Path to the file containing contig sequences to be
        analyzed.
        others_db_path (str): Path to the BLAST database against which the
        contigs will be queried.
        sample (str): Name of the sample being processed, used for
        identification purposes.
        outfile_suffix (str): Suffix to append to the output file name for
        distinction.

    Returns:
        str: Path to the output file generated by BLASTx.
    """
    outfile = f"{sample}_{outfile_suffix}"
    command_line = (f"blastx -db {others_db_path} -query {contig_file}"
                    f" -evalue 0.001 -out {outfile}")
    try:
        run(command_line, shell=True)
    except Exception as error:
        raise Exception(f"{error}")

    return outfile
